/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app_work1;

public class App {
    public String getGreeting() {
        return "Hello World Gradle on VS Code!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
