/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app_work1;

public class App {
    public String getGreeting() {
        return "Hello World Gradle on VS Code!";
    }

    public int maltiplication(int x,int y) {
        return x * y;
    }

    public int division(int x,int y) {
        return x / y;
    }

    public static void main(String[] args) {
        int x;
        x = new App().maltiplication(5, 6);
        System.out.println(new App().getGreeting());
        System.out.println(x);
    };
}
