# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: cd app_work1 && chmod +x gradlew
      
    - name: Build with Gradle
      run: cd app_work1 && ./gradlew build
      
    - name: Run Hello World Test
      run: cd app_work1 && ./gradlew test --stacktrace

      
    - name: Run Hello World Test.maltiplicationTest
      run: cd app_work1/app && ../gradlew test --tests app_work1.AppTest.maltiplicationTest

    - name: Run Hello World 
      run: cd app_work1 && ./gradlew run
      
  

